### ISSUE TITLE
The data link and the model link are the same.

### ISSUE THREAD

**Issue by HHW-zhou** [MangoKiller/MolTC#2]
The data link and the model link are the same.

**Comment by MangoKiller** [comment]
> The data link and the model link are the same.



> The data link and the model link are the same.

Thank you for your attention! 
The current code is related to the **MolTC** model, and it includes **scattered** download links in each submodule for the corresponding datasets required. 
We are updating the integrated dataset MoT-instructions to the latest version, which will be displayed soon. 
Fortunately, its temporary absence will not affect the operation of the MolTC model at all, and you can run MolTC directly. 
Thank you once again for your attention! :)

**Comment by MangoKiller** [comment]
> The data link and the model link are the same.


I just checked again, and the two links point to the same place. I will update them within two days.

**Comment by MangoKiller** [comment]
> The data link and the model link are the same.

Done! Thanks!
